### ISSUE TITLE
Windows 11 23H2

### ISSUE THREAD

**Issue by ronmanp** [okieselbach/SyncMLViewer#4]
Hi, thanks for that great tool. 

I just tried it on Windows 10 22H2 (19045.3693) and it works as expected however Windows 11 23H2 (22631.2861) doesn't return anything when I hit the MDM sync button. I also tried running the MDM sync outside of the tool but it still returns nothing in SyncML Viewer. 

Both machines running Intune extension 1.73.202.0.  Devices are both Hybrid Joined and co-managed if that makes any difference.

**Comment by okieselbach** [comment]
Hi, first of all, thanks for the feedback! So, I'm running a 23H2 machine myself and it starts the sync process for MDM and MMP-C. I'm running a cloud-only device. So, the difference is you are running a hybrid joined (domain joined and cloud attached) device which is co-managed and the workloads are moved over to Intune? So, I assume the device is receiving indeed their configuration profiles via Intune instead of GPOs. This is verified also with the native MDM Sync button in Settings. 
The sync is simply triggering the scheduled task here: "Microsoft\Windows\EnterpriseMgmt\{MDM-Enrollment-ID}\\Schedule #3 created by enrollment client"

**Comment by Tokagero** [comment]
Hi Oliver, first thanks for the great tool !
I see the same as ronmanp with W11 23H2 with version 1.0.9 while 1.0.8 works fine. To give some details: I am using Workspace ONE instead of Intune. It seems with 1.0.9 something changed for the  OMA-DM AccountID detection. While this shows correct in 1.0.8 in the MDM Diagnostics Tab , it is blank for 1.0.9.
Maybe this can be changed so the MDM sync button works for other MDM Management solutions again ? 
Workaround for now is to trigger the task or use the native MDM Sync Button in Settings.

**Comment by okieselbach** [comment]
Hi,

Yes, indeed I added some logic to detect the Account ID differently. When using an Intune environment, we have to deal with some dual enrollment states which result in more than 1 enrollment ID in the registry. But the new detection broke your scenario when it is not an Intune enrollment. I added back some logic to detect the Account ID differently if my first enumeration fails. Furthermore, I added a fallback routine to trigger the MDM Sync the same way I used in 1.0.8 via direct API call. 

This alternate MDM trigger can also be enforced via menu item:

![image](https://github.com/okieselbach/SyncMLViewer/assets/26136457/f46aa2da-faa2-4214-9441-34d3020191e5)

I hope the issues are solved with this for you both since version 1.1.0. Let me know ✌️

**Comment by Tokagero** [comment]
Hi Oliver, yes this solved it !
Thanks for looking into this and interesting to read about the dual enrollment states and MMP-C. Both the MDM Sync and alternate MDM trigger work fine now for me. Always finding something new and interesting with your tool.

**Comment by okieselbach** [comment]
Happy to hear this and happy to take any feedback. Let me know if there is something, like a bug or feature suggestion.
